---
driver:
  name: docker

provisioner:
  name: chef_zero

platforms:
  - name: centos-6.8
    driver:
#       dockerfile: C7SystemDWithNetwork.docker
#       privileged: true
#       run_command: /usr/sbin/init
       use_sudo: false
       network:
       - ["private network", { ip: "172.17.0.2" }]

suites:
  - name: default
    run_list:
      - recipe[git::default]
      - recipe[jenkinsjava::default]
    attributes:
