---
driver:
  name: docker

provisioner:
  name: chef_zero

platforms:
  - name: centos-6.8
    driver:
       use_sudo: false
       network:
       - ["private network", { ip: "172.17.0.2" }]

suites:
  - name: default
    run_list:
      - recipe[jenkinsjava::default]
    attributes:
